name: Deploy to GitHub Pages

on:
 push:
   branches:
     - main

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout repository
     uses: actions/checkout@v2

   - name: List files for debugging
     run: ls -la
     shell: /usr/bin/bash -e {0}

   - name: Copy HTML, CSS, and JS files to src
     run: |
       mkdir -p src
       cp -r src/HTML/* src/
       cp -r src/Style/* src/
       cp -r src/Script/* src/
     shell: /usr/bin/bash -e {0}

   - name: List files in src for debugging
     run: ls -la src
     shell: /usr/bin/bash -e {0}

   - name: Upload artifact
     uses: actions/upload-pages-artifact@v3
     with:
       path: src
       name: github-pages
       retention-days: 1
     env:
       GITHUB_PAGES: true

   - name: Archive artifact
     run: |
       echo ::group::Archive artifact
       tar \
         --dereference --hard-dereference \
         --directory "$INPUT_PATH" \
         -cvf "$RUNNER_TEMP/artifact.tar" \
         --exclude=.git \
         --exclude=.github \
         .
       echo ::endgroup::
     shell: /usr/bin/sh -e {0}
     env:
       GITHUB_PAGES: true
       INPUT_PATH: src
